USE master;
GO

IF DB_ID(N'BookStreamDB') IS NOT NULL
BEGIN
    ALTER DATABASE BookStreamDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE BookStreamDB;
END
GO

CREATE DATABASE BookStreamDB;
GO

USE BookStreamDB;
GO

SELECT DB_NAME() AS CurrentDatabase;
GO
